django_energysystem_viewer/urls.py
from django.urls import path

from django_energysystem_viewer import views

app_name = "django_energysystem_viewer"


urlpatterns = [
    path("energysystem/selection/", views.SelectionView.as_view(), name="selection"),
    path("energysystem/network/", views.network, name="networks"),
    path("energysystem/network_graph/", views.network_graph),
    path("energysystem/abbreviation_meaning/", views.abbreviation_meaning),
    path("energysystem/aggregation/", views.AggregationView.as_view(), name="aggregations"),
    path("energysystem/aggregation_graph/", views.aggregation_graph),
    path("energysystem/lod_list/", views.write_lod_list, name="lod_list"),
    path("energysystem/processes/", views.ProcessesView.as_view(), name="processes"),
    path(
        "energysystem/process/<str:process_name>/data/",
        views.ProcessDetailView.as_view(),
    ),
    path("energysystem/artifacts/", views.ArtifactsView.as_view(), name="artifacts"),
    path(
        "energysystem/artifact/<str:group_name>/<str:artifact_name>/data/",
        views.ArtifactDetailView.as_view(),
    ),
    path(
        "energysystem/artifact/<str:group_name>/<str:artifact_name>/<str:version>/data/",
        views.ArtifactDetailView.as_view(),
    ),
]

django_energysystem_viewer/templates/django_energysystem_viewer/aggregation.html
{% extends "django_energysystem_viewer/base.html" %}

{% load static %}

{% block content %}
  <div class="container aggregation">
    <h1 class="d-flex align-items-center">
      <svg width="32" height="32" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="67" cy="67" r="66" fill="#DDDCF3"/>
        <rect x="85.9707" y="76.6569" width="16" height="16" transform="rotate(45 85.9707 76.6569)" stroke="black" stroke-width="8"/>
        <rect x="43.9707" y="76.6569" width="16" height="16" transform="rotate(45 43.9707 76.6569)" stroke="black" stroke-width="8"/>
        <rect x="85.9707" y="53.6569" width="16" height="16" transform="rotate(45 85.9707 53.6569)" stroke="black" stroke-width="8"/>
        <rect x="43.9707" y="54.6569" width="16" height="16" transform="rotate(45 43.9707 54.6569)" stroke="black" stroke-width="8"/>
        <rect x="85.9707" y="30.6569" width="16" height="16" transform="rotate(45 85.9707 30.6569)" stroke="black" stroke-width="8"/>
      </svg>
      <span class="ms-3">
        Aggregation Graph
      </span>
    </h1>
    <section class="aggregation__options">
      <form id="aggregation_form">
        <label for="lod" class="pe-1">Desired level of detail:</label>
        <span class="pe-1">
          <input type="radio" id="lod" name="lod" value=1>
          <label for="lod">1</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="lod" name="lod" value=2 checked>
          <label for="lod">2</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="lod" name="lod" value=3>
          <label for="lod" class="pe-5">3</label>
        </span>
        <span class="pe-1">
          <input type="hidden" name="structure" value="{{ structure_name }}" />
          <label for="sectors">Sector:</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="sectors" name="sectors" value="pow" checked>
          <label for="sectors">Power</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="sectors" name="sectors" value="x2x">
          <label for="sectors">X2X</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="sectors" name="sectors" value="hea">
          <label for="sectors">Heat</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="sectors" name="sectors" value="ind">
          <label for="sectors">Industry</label>
        </span>
        <span class="pe-1">
          <input type="radio" id="sectors" name="sectors" value="tra">
          <label for="sectors" class="pe-5">Transport</label>
        </span>
      </form>
      <div class="aggregation__button">
        <span class="pe-2">
          Processes from all sectors for level of detail:
        </span>
        <button id="download_button" class="btn button button--secondary">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
          </svg>
          <span class="ps-2">
            Download
          </span>
        </button>
      </div>
    </section>
    
    <section class="aggregation__graph">
      <div id="aggregation_graph" style="width: auto; height: 900px"></div>
      <div id="legend">
        <!-- Legend content will be dynamically inserted here -->
        </div>
    </section>

  </div>
{% endblock content %}

{% block javascript %}
  <script src="{% static "django_energysystem_viewer/libs/htmx.min.js" %}"></script>
  <script src="{% static 'vendors/cytoscape/js/cytoscape.min.js' %}"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
        const cy = cytoscape({
            container: document.getElementById('aggregation_graph'),
            style: [
              { selector: 'node', style: {'label': 'data(id)', 'font-size': '100', 'width': '75', 'height': '75'} },
              { selector: '.aggregation_level_1', style: {'background-color': 'green'} },
              { selector: '.aggregation_level_2', style: {'background-color': 'blue'} },
              { selector: '.aggregation_level_3', style: {'background-color': 'red'} },
              { selector: '.collapsed', style: {'background-color': 'orange'} },
              { selector: '.aggregation_step_1', style: {'line-color': 'green'} },
              { selector: '.aggregation_step_2', style: {'line-color': 'blue'} },
              { selector: '.aggregation_step_3', style: {'line-color': 'red'} },
            ],
            elements: []
        });

        const aggregation_form = document.getElementById("aggregation_form");
        aggregation_form.addEventListener("change", updateAggregationGraph);

        function updateAggregationGraph() {
            console.log("Get aggregation data")
            const formData = new FormData(aggregation_form);
            const url = "/energysystem/aggregation_graph";

            // Append form data to URL
            const queryString = new URLSearchParams(formData).toString();
            var requestUrl = url + "?" + queryString;

            fetch(requestUrl)
                .then(response => response.json())
                .then(data => {
                    console.log("Received data:", data);
                    cy.elements().remove(); // Clear existing elements first
                    cy.add(data.elements);  // Add new nodes and edges
                    cy.layout({
                        name: 'preset',
                        fit: true
                    }).run();
                    cy.fit(); // This will automatically zoom out to fit all elements
                    cy.resize(); // This ensures the viewport is recalculated in case of container size changes
                })
                .catch(error => console.error('Error requesting aggregation data:', error));
        }

        const download_button = document.getElementById("download_button");
        download_button.addEventListener("click", function() {
            const formData = new FormData(aggregation_form);
            const url = "/energysystem/lod_list";

            // Append form data to URL
            const queryString = new URLSearchParams(formData).toString();
            var downloadUrl = url + "?" + queryString;

            window.location.href = downloadUrl;
            });
    });

    document.addEventListener("DOMContentLoaded", function() {
    const legendData = {
        'pow': [
            { text: 'renewable type', color: 'blue' },
            { text: 'fuel/potential type', color: 'green' }
        ],
        'x2x': [
            { text: 'technology type', color: 'green' }
        ],
        'hea': [
            { text: 'technology type', color: 'blue' },
            { text: 'building types', color: 'green' },
        ],
        'ind': [
            { text: 'process route', color: 'brown' }
        ],
        'tra': [
            { text: 'fuel type', color: 'red' },
            { text: 'vehicle size', color: 'blue' },
            { text: 'distance type', color: 'green' }
        ]
    };

    const sectorNames = {
        'pow': 'Power',
        'x2x': 'X2X',
        'hea': 'Heat',
        'ind': 'Industry',
        'tra': 'Transport'
    };

    const legendContainer = document.getElementById("legend");

    function updateLegend(sector) {
        const sectorFullName = sectorNames[sector];
        legendContainer.innerHTML = `<div class="pb-2">Aggregations ${sectorFullName} Sector:</div>`;
        legendData[sector].forEach(item => {
            legendContainer.innerHTML += 
            `<div class="d-flex align-items-center">
            <span style="margin-right: 0.5rem; height: 0.75rem; width: 0.75rem; border-radius: 0.75rem; background-color: ${item.color}"></span>
            <span style="color: ${item.color};">${item.text}</span>
            </div>`;
        });
    }

    const aggregation_form = document.getElementById("aggregation_form");
    aggregation_form.addEventListener("change", function() {
        const sector = document.querySelector('input[name="sectors"]:checked').value;
        updateLegend(sector);
        updateAggregationGraph();
    });

    // Initialize the legend with the default sector
    updateLegend(document.querySelector('input[name="sectors"]:checked').value);
});



  </script>
{% endblock javascript %}

django_energysystem_viewer/templates/django_energysystem_viewer/artifact_data.html
{% load partials %}

{% startpartial processes inline=True %}
<div id="artifact-processes">
  {% if processes %}
    <h3>Related processes:</h3>
    <ul>
      {% for process in processes %}
        <li>
          <a href="{% url 'django_energysystem_viewer:processes' collection_name=collection_name %}?process={{ process }}">{{ process }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</div>
{% endpartial %}
{% startpartial artifact_data inline=True %}
<div class="tab-pane fade show active"
     id="artifact-data"
     role="tabpanel"
     aria-labelledby="artifact-data-tab">
  {% if data %}
    {{ data | safe }}
  {% else %}
    Select artifact to show related data
  {% endif %}
</div>
<div class="tab-pane fade"
     id="artifact-metadata"
     role="tabpanel"
     aria-labelledby="artifact-metadata-tab">
  {% if metadata %}
    {{ metadata | safe }}
  {% else %}
    Select artifact to show related metadata
  {% endif %}
</div>
{% endpartial %}

django_energysystem_viewer/templates/django_energysystem_viewer/artifact_detail.html
{% load partials %}

<h2 class="d-flex align-items-center">
  <svg width="32" height="32" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="67" cy="67" r="66" fill="#D7E1F4"/>
    <rect x="31.76" y="78.1571" width="22.3982" height="22.3982" stroke="black" stroke-width="8"/>
    <circle cx="87.7964" cy="44.5188" r="12.719" stroke="black" stroke-width="8"/>
    <path d="M87.4164 82.5416L88.1336 84.7489L89.0317 87.5129H91.9378H94.2588L92.3811 88.8771L90.03 90.5853L90.928 93.3492L91.6452 95.5566L89.7675 94.1924L87.4164 92.4842L85.0653 94.1924L83.1876 95.5566L83.9048 93.3492L84.8028 90.5853L82.4517 88.8771L80.574 87.5129H82.895H85.8011L86.6992 84.7489L87.4164 82.5416Z" stroke="black" stroke-width="8"/>
    <path d="M53.7782 55.3603L35 44.5187L53.7782 33.6771L53.7782 55.3603Z" stroke="black" stroke-width="8"/>
  </svg>
  <span class="ms-3">
    Artifact data
  </span>
</h2>
<div id="artifact-processes">
  {% if processes %}
    <h3>Related processes:</h3>
    <ul>
      {% for process in processes %}
        <li>
          <a href="{% url 'django_energysystem_viewer:processes' %}?collection={{ collection_name }}&structure={{ structure_name }}&process={{ process }}">{{ process }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</div>
<nav>
  <div class="nav nav-tabs" role="tablist">
    <button class="nav-link active"
            id="artifact-data-tab"
            data-bs-toggle="tab"
            data-bs-target="#artifact-data"
            type="button"
            role="tab"
            aria-controls="artifact-data"
            aria-selected="true">Data</button>
    <button class="nav-link"
            id="artifact-metadata-tab"
            data-bs-toggle="tab"
            data-bs-target="#artifact-metadata"
            type="button"
            role="tab"
            aria-controls="artifact-metadata"
            aria-selected="false">Metadata</button>
  </div>
</nav>
<div class="tab-content">
  <div class="tab-pane fade show active"
       id="artifact-data"
       role="tabpanel"
       aria-labelledby="artifact-data-tab">
    {% if data %}
      {{ data | safe }}
    {% else %}
    <div class="tab-content--empty">
      <svg width="48" height="48" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="17" y="79" width="36" height="36" stroke="#676C73" stroke-width="4"/>
        <circle cx="94" cy="38" r="20" stroke="#676C73" stroke-width="4"/>
        <path d="M93.5 77.4721L97.5475 89.9291L97.9965 91.3111H99.4496H112.548L101.951 99.0099L100.776 99.864L101.225 101.246L105.272 113.703L94.6756 106.004L93.5 105.15L92.3244 106.004L81.7279 113.703L85.7754 101.246L86.2245 99.864L85.0489 99.0099L74.4524 91.3111H87.5504H89.0035L89.4525 89.9291L93.5 77.4721Z" stroke="#676C73" stroke-width="4"/>
        <path d="M52.5 57.9186L18 38L52.5 18.0814L52.5 57.9186Z" stroke="#676C73" stroke-width="4"/>
      </svg>
      <span>
        Select artifact to show related data
      </span>
    </div>
    {% endif %}
  </div>
  <div class="tab-pane fade"
       id="artifact-metadata"
       role="tabpanel"
       aria-labelledby="artifact-metadata-tab">
    {% if metadata %}
      {{ metadata | safe }}
    {% else %}
    <div class="tab-content--empty">
      <svg width="48" height="48" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="17" y="79" width="36" height="36" stroke="#676C73" stroke-width="4"/>
        <circle cx="94" cy="38" r="20" stroke="#676C73" stroke-width="4"/>
        <path d="M93.5 77.4721L97.5475 89.9291L97.9965 91.3111H99.4496H112.548L101.951 99.0099L100.776 99.864L101.225 101.246L105.272 113.703L94.6756 106.004L93.5 105.15L92.3244 106.004L81.7279 113.703L85.7754 101.246L86.2245 99.864L85.0489 99.0099L74.4524 91.3111H87.5504H89.0035L89.4525 89.9291L93.5 77.4721Z" stroke="#676C73" stroke-width="4"/>
        <path d="M52.5 57.9186L18 38L52.5 18.0814L52.5 57.9186Z" stroke="#676C73" stroke-width="4"/>
      </svg>
      <span>
        Select artifact to show related metadata
      </span>
    </div>
    {% endif %}
  </div>
</div>

django_energysystem_viewer/templates/django_energysystem_viewer/artifacts.html
{% extends "django_energysystem_viewer/base.html" %}

{% load static partials %}

{% block content %}
  <div class="container process">
    <header class="process__header">
      <h1>Collection "{{ collection_name }}"</h1>
      <a href="{{ collection_url }}"
          class="mb-4 button button--link"
          target="_blank">
        <span class="pe-2">View collection</span>
        <svg xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              class="bi bi-box-arrow-up-right"
              viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5" />
          <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0z" />
        </svg>
      </a>
    </header>
    <div class="container process__main">
      <div class="d-flex flex-row">
        <section class="process__sidebar">
          {% regroup artifacts by group as artifacts_grouped %}
          {% for group in artifacts_grouped %}
            <h2>{{ group.grouper }}</h2>
            <ul>
              {% for artifact in group.list %}
                <li>
                  <button class="btn btn-link"
                          hx-get="/energysystem/artifact/{{ artifact.group }}/{{ artifact.artifact }}/{{ artifact.version }}/data?collection={{ collection_name }}"
                          hx-target="#artifact-detail">{{ artifact.artifact }} ({{ artifact.version }})</button>
                </li>
              {% endfor %}
            </ul>
          {% endfor %}
        </section>
        <section class="process__graph" id="artifact-detail">{% include "django_energysystem_viewer/artifact_detail.html" %}</section>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static "django_energysystem_viewer/libs/htmx.min.js" %}"></script>
  <script src="{% static "vendors/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendors/datatables/dataTables.js" %}"></script>
  <script src="{% static "vendors/json-viewer/jquery.json-viewer.js" %}"></script>
  <script src="{% static "js/tables.js" %}"></script>
{% endblock javascript %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "vendors/datatables/dataTables.css" %}" />
  <link rel="stylesheet" href="{% static "vendors/json-viewer/jquery.json-viewer.css" %}" />
{% endblock css %}

django_energysystem_viewer/templates/django_energysystem_viewer/process_detail.html
<h2 class="d-flex align-items-center">
  <svg width="32" height="32" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="67" cy="67" r="66" fill="#F2E7C8"/>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M74.9218 70.9643C78.8221 74.9123 84.7128 80.0324 90.5565 80.0324C102.387 80.0324 108.337 65.9709 99.9734 57.7851C97.5635 55.4264 94.2343 53.9676 90.5565 53.9676C81.3361 53.9676 71.5117 66.7806 65.3567 73.5154C59.9438 79.3722 51.8063 87 42.4481 87C24.304 87 15.1574 65.4271 27.9998 52.8576C31.6961 49.2398 36.805 47.0008 42.4481 47.0008C50.4043 47.0008 57.5304 52.5564 62.8093 57.8286L58.0934 63.0503C54.1894 59.0987 48.2948 53.9714 42.4445 53.9714C30.6138 53.9714 24.6639 68.0328 33.0275 76.2187C35.4374 78.5773 38.7667 80.0361 42.4445 80.0361C51.8577 80.0361 62.0122 66.5952 68.4073 59.6643C73.8091 53.9382 81.6246 47 90.5519 47C108.696 47 117.843 68.5729 105 81.1424C101.304 84.7602 96.195 86.9992 90.5519 86.9992C82.6031 86.9992 75.481 81.4509 70.2021 76.1853L74.9218 70.9643Z" fill="black"/>
  </svg>
  <span class="ms-3">
    Process data
  </span>
</h2>
<div id="process-artifacts">
  {% if artifacts %}
    <h3>Related artifacts:</h3>
    <ul>
      {% for artifact in artifacts %}
        <li>
          <a href="{% url 'django_energysystem_viewer:artifacts' %}?collection={{ collection_name }}&structure={{ structure_name }}&group={{ artifact.group }}&artifact={{ artifact.artifact }}">{{ artifact.artifact }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</div>
<nav>
  <div class="nav nav-tabs" role="tablist">
    <button class="nav-link active"
            id="process-scalars-tab"
            data-bs-toggle="tab"
            data-bs-target="#process-scalars"
            type="button"
            role="tab"
            aria-controls="process-scalars"
            aria-selected="true">Scalars</button>
    <button class="nav-link"
            id="process-timeseries-tab"
            data-bs-toggle="tab"
            data-bs-target="#process-timeseries"
            type="button"
            role="tab"
            aria-controls="process-timeseries"
            aria-selected="false">Timeseries</button>
  </div>
</nav>
<div class="tab-content">
  <div class="tab-pane fade show active"
       id="process-scalars"
       role="tabpanel"
       aria-labelledby="process-scalars-tab">
    {% if scalars %}
      {{ scalars | safe }}
    {% else %}
      <div class="tab-content--empty">
        <svg width="48" height="48" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M95.0987 36.5987C92.2028 36.2602 76.588 39.1143 79.0827 43.6247V43.6195C79.3639 44.0987 79.8222 44.4476 80.3587 44.5831C80.8951 44.7237 81.4629 44.6403 81.942 44.3591C85.9264 42.0154 90.468 40.7758 95.0983 40.7758C129.416 42.1924 129.437 91.1144 95.0983 92.5358H95.0931C88.2338 92.5306 81.6558 89.8014 76.8064 84.9472C71.9523 80.0983 69.2231 73.5202 69.2179 66.6552C69.2075 58.5667 65.9887 50.8059 60.2648 45.0872C54.546 39.3632 46.7861 36.1446 38.6968 36.1342C-1.77652 37.806 -1.79252 95.4982 38.6968 97.1755C41.5771 97.4307 56.6035 94.988 54.2755 90.5192C53.713 89.5088 52.4421 89.1495 51.4317 89.7067C47.5359 91.8682 43.1506 92.9984 38.6974 92.9984C3.76535 91.561 3.74935 41.7584 38.6974 40.3158C45.6766 40.321 52.3747 43.097 57.312 48.0398C62.2547 52.9772 65.0308 59.67 65.036 66.6544C65.0464 74.6232 68.2183 82.2638 73.8538 87.8998C79.4892 93.5352 87.1246 96.7071 95.0991 96.7175C134.959 95.0716 134.973 38.2494 95.0987 36.5987Z" fill="#676C73"/>
        </svg>
        Select process to show related scalar data
      </div>
    {% endif %}
  </div>
  <div class="tab-pane fade"
       id="process-timeseries"
       role="tabpanel"
       aria-labelledby="process-timeseries-tab">
    {% if timeseries %}
      {{ timeseries | safe }}
    {% else %}
      <div class="tab-content--empty">
        <svg width="48" height="48" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M95.0987 36.5987C92.2028 36.2602 76.588 39.1143 79.0827 43.6247V43.6195C79.3639 44.0987 79.8222 44.4476 80.3587 44.5831C80.8951 44.7237 81.4629 44.6403 81.942 44.3591C85.9264 42.0154 90.468 40.7758 95.0983 40.7758C129.416 42.1924 129.437 91.1144 95.0983 92.5358H95.0931C88.2338 92.5306 81.6558 89.8014 76.8064 84.9472C71.9523 80.0983 69.2231 73.5202 69.2179 66.6552C69.2075 58.5667 65.9887 50.8059 60.2648 45.0872C54.546 39.3632 46.7861 36.1446 38.6968 36.1342C-1.77652 37.806 -1.79252 95.4982 38.6968 97.1755C41.5771 97.4307 56.6035 94.988 54.2755 90.5192C53.713 89.5088 52.4421 89.1495 51.4317 89.7067C47.5359 91.8682 43.1506 92.9984 38.6974 92.9984C3.76535 91.561 3.74935 41.7584 38.6974 40.3158C45.6766 40.321 52.3747 43.097 57.312 48.0398C62.2547 52.9772 65.0308 59.67 65.036 66.6544C65.0464 74.6232 68.2183 82.2638 73.8538 87.8998C79.4892 93.5352 87.1246 96.7071 95.0991 96.7175C134.959 95.0716 134.973 38.2494 95.0987 36.5987Z" fill="#676C73"/>
        </svg>
        <span>
          Select process to show related timeseries data
        </span>
      </div>
    {% endif %}
  </div>
</div>

django_energysystem_viewer/templates/django_energysystem_viewer/selection.html
{% extends "base.html" %}

{% block content %}
  <div class="selection">
    <h1>Selections:</h1>
    <form method="get">
      {% csrf_token %}
      <div class="selection__item">
        <label for="structures">Structure</label>
        <select class="form-select" id="structure" name="structure">
          {% for structure in structure_list %}<option label="{{ structure }}">{{ structure }}</option>{% endfor %}
        </select>
      </div>
      <div class="selection__item">
        <label for="collection">Collection</label>
        <select class="form-select" id="collection" name="collection">
          {% for collection in collection_list %}<option label="{{ collection }}">{{ collection }}</option>{% endfor %}
        </select>
      </div>
      <div class="selection__item">
        <button class="btn button button--primary"
                type="submit"
                formaction="{% url 'django_energysystem_viewer:aggregations' %}">Look at Aggregation</button>
        <button class="btn button button--primary"
                type="submit"
                formaction="{% url 'django_energysystem_viewer:networks' %}">Look at Network</button>
        <button class="btn button button--primary"
                type="submit"
                formaction="{% url 'django_energysystem_viewer:processes' %}">Look at Processes</button>
        <button class="btn button button--primary"
                type="submit"
                formaction="{% url 'django_energysystem_viewer:artifacts' %}">Look at Artifacts</button>
      </div>
    </form>
  </div>
{% endblock content %}